#!/bin/bash

sudo apt install libopenjfx-java=8u161-b12-1ubuntu2

# Install coursier
curl -L -o coursier https://git.io/coursier-cli
chmod +x coursier

# Prefetch packages used in slides
coursier fetch -e 2.12.8 \
  org.apache.spark::spark-sql:2.4.3 \
  sh.almond::almond-spark:0.5.0 \
  org.plotly-scala::plotly-almond:0.7.0 \
  io.github.stanch::reftree:1.4.0 \
  org.typelevel::squants:1.4.0

# We have to build Vegas locally until we have a 2.12 release (https://github.com/vegas-viz/Vegas/issues/106)
COURSIER_EXPERIMENTAL=1 ./coursier install sbt-launcher
COURSIER_EXPERIMENTAL=1 $(./coursier install-path) >> $HOME/.bashrc && source $HOME/.bashrc
git clone https://github.com/vegas-viz/Vegas.git
cd Vegas
sbt '++2.12.8 publishLocal'
cd ..
rm -rf Vegas

# Install almond for Scala 2.12
SCALA_VERSION=2.12.8 ALMOND_VERSION=0.5.0
./coursier bootstrap \
  -r jitpack \
  -i user -I user:sh.almond:scala-kernel-api_$SCALA_VERSION:$ALMOND_VERSION \
  sh.almond:scala-kernel_$SCALA_VERSION:$ALMOND_VERSION \
  --sources --default=true \
  -o almond
./almond --install \
  --command "java -XX:MaxRAMPercentage=80.0 -jar almond" \
  --copy-launcher \
  --metabrowse
rm -f almond


# Install almond for Scala 2.11
SCALA_VERSION=2.11.12 ALMOND_VERSION=0.5.0
./coursier bootstrap \
  -r jitpack \
  -i user -I user:sh.almond:scala-kernel-api_$SCALA_VERSION:$ALMOND_VERSION \
  sh.almond:scala-kernel_$SCALA_VERSION:$ALMOND_VERSION \
  --sources --default=true \
  -o almond-scala-2.11
./almond-scala-2.11 --install --id scala211 --display-name "Scala (2.11)" \
  --command "java -XX:MaxRAMPercentage=80.0 -jar almond-scala-2.11 --id scala211 --display-name 'Scala (2.11)'" \
  --copy-launcher \
  --metabrowse
rm -f almond-scala-2.11

# Set indentation to two spaces
JUPYTER_CONFIG_DIR=$(jupyter --config-dir)
# Classic notebook
mkdir -p $JUPYTER_CONFIG_DIR/nbconfig/
cat > $JUPYTER_CONFIG_DIR/nbconfig/notebook.json <<- EOF
{
  "CodeCell": {
    "cm_config": {
      "indentUnit": 2
    }
  }
}
EOF
# JupyterLab notebook
mkdir -p $JUPYTER_CONFIG_DIR/lab/user-settings/@jupyterlab/notebook-extension/
cat > $JUPYTER_CONFIG_DIR/lab/user-settings/@jupyterlab/notebook-extension/tracker.jupyterlab-settings <<- EOF
{
    "codeCellConfig": {
      "tabSize": 2
    }
}
EOF
# JupyterLab editor
mkdir -p $JUPYTER_CONFIG_DIR/lab/user-settings/@jupyterlab/fileeditor-extension/
cat > $JUPYTER_CONFIG_DIR/lab/user-settings/@jupyterlab/fileeditor-extension/plugin.jupyterlab-settings <<- EOF
{
    "editorConfig": {
      "tabSize": 2,
    }
}
EOF

# Install required Jupyter/JupyterLab extensions
jupyter labextension install @jupyterlab/plotly-extension
jupyter contrib nbextension install --user
jupyter nbextension enable splitcell/splitcell

# Workaround for https://github.com/damianavila/RISE/issues/479
cp rise.css $JUPYTER_CONFIG_DIR/custom/custom.css